pipeline:
  name: Install AZ CLI via Curl
  identifier: Install_AZ_CLI_via_Curl
  projectIdentifier: MyProject
  orgIdentifier: MyOrg
  stages:
    - stage:
        name: Install AZ CLI
        identifier: Install_AZ_CLI
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Download and Install Azure CLI
                  identifier: install_az_cli
                  spec:
                    shell: Bash
                    onDelegate: true
                    delegateSelectors: []  # Optional: add tag if using a specific delegate
                    command: |
                      echo "Installing Azure CLI using Microsoft install script..."

                      # Download and run the install script
                      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

                      echo "Checking az version:"
                      az version