pipeline:
  name: Delegate Connectivity Test
  identifier: delegate_connectivity_test
  projectIdentifier: your_project_id      # Change to your project
  orgIdentifier: your_org_id              # Change to your org
  variables:
    - name: TARGET_SERVER
      type: String
      default: example.com               # Change default or override on run
  stages:
    - stage:
        name: Connectivity Check Stage
        identifier: connectivity_check_stage
        type: Deployment                  # You can use CI if preferred
        spec:
          execution:
            steps:
              - step:
                  name: DNS and SSH Check
                  identifier: dns_ssh_check
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Checking DNS resolution for $TARGET_SERVER..."
                          nslookup $TARGET_SERVER
                          echo ""

                          echo "Checking SSH connectivity to $TARGET_SERVER on port 22..."
                          ssh -o BatchMode=yes -o ConnectTimeout=5 $TARGET_SERVER echo "SSH connection successful" || echo "SSH connection failed"
