apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      imagePullSecrets:
        - name: regcred  # Use your image pull secret
      volumes:
        - name: secret-vol
          secret:
            secretName: my-secret
            items:
              - key: secret-key
                path: secret.txt
        - name: shared-vol
          emptyDir: {}
      initContainers:
        - name: init-downloader
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Downloading ZIP..."
              wget -O /shared/myfile.zip http://example.com/file.zip
              echo "Unzipping..."
              unzip -oq /shared/myfile.zip -d /shared/
          volumeMounts:
            - name: shared-vol
              mountPath: /shared
      containers:
        - name: app
          image: openjdk:17
          command: ["/bin/sh", "-c"]
          args:
            - |
              export JAVA_TOOL_OPTIONS="-Dsecret=$(cat /secret/secret.txt)" && \
              echo "Pod running..." && \
              sleep infinity
          volumeMounts:
            - name: secret-vol
              mountPath: /secret
              readOnly: true
            - name: shared-vol
              mountPath: /shared
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"


---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  secret-key: bXlTZWNyZXRUb2tlbjEyMw==
