apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      volumes:
        - name: secret-vol
          secret:
            secretName: my-secret
            items:
              - key: secret-key
                path: secret.txt

      containers:
        - name: app
          image: openjdk:17
          command: ["/bin/sh", "-c"]
          args:
            - |
              export JAVA_TOOL_OPTIONS="-Dsecret=$(cat /secret/secret.txt)" && \
              java -jar /app/app.jar
          volumeMounts:
            - name: secret-vol
              mountPath: /secret
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  secret-key: bXlTZWNyZXRUb2tlbjEyMw==
