apiVersion: apps/v1
kind: Deployment
metadata:
  name: unzip-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unzip-demo
  template:
    metadata:
      labels:
        app: unzip-demo
    spec:
      containers:
        - name: main
          image: openjdk:17
          command: ["/bin/sh", "-c", "echo 'Running forever...'; tail -f /dev/null"]
          env:
            - name: SECRET_VALUE
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: secret-key
            - name: JAVA_TOOL_OPTIONS
              value: "-Dsecret=$(SECRET_VALUE)"
          volumeMounts:
            - name: shared-vol
              mountPath: /shared
            - name: secret-vol
              mountPath: /secrets
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      initContainers:
        - name: init-downloader
          image: alpine:3.20
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache wget unzip && \
              echo "Downloading zip..." && \
              wget -O /shared/myfile.zip http://example.com/path/to/artifact.zip && \
              echo "Unzipping..." && \
              unzip -oq /shared/myfile.zip -d /shared/
          volumeMounts:
            - name: shared-vol
              mountPath: /shared

      volumes:
        - name: shared-vol
          emptyDir: {}
        - name: secret-vol
          secret:
            secretName: my-secret

      imagePullSecrets:
        - name: regcred


---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  secret-key: bXlTZWNyZXRUb2tlbjEyMw==
