pipeline:
  name: PowerShellMatrixPipeline
  identifier: PowerShellMatrixPipeline
  projectIdentifier: YourProject
  orgIdentifier: YourOrg
  stages:
    - stage:
        name: MatrixPowerShell
        identifier: MatrixPowerShell
        type: Deployment
        spec:
          deploymentType: CustomDeployment
          customDeploymentRef:
            templateRef: YourCustomDeployment
            versionLabel: "1"
          infrastructure:
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: YourK8sConnector
                namespace: default
                releaseName: release-${infra.kubernetes.namespace}
          execution:
            steps:
              - step:
                  name: Run PowerShell Per Server
                  identifier: PerServerPowerShell
                  type: Command
                  strategy:
                    matrix:
                      server: ["server1.domain.local", "server2.domain.local", "server3.domain.local"]
                  spec:
                    shell: PowerShell
                    command: |
                      $server = "<+matrix.server>"
                      Write-Host "`nConnecting to $server..."
                      $username = "<+secrets.getValue("win_user")>"
                      $password = ConvertTo-SecureString "<+secrets.getValue("win_pass")>" -AsPlainText -Force
                      $creds = New-Object System.Management.Automation.PSCredential ($username, $password)

                      Invoke-Command -ComputerName $server -Credential $creds -ScriptBlock {
                          Get-Date
                          Get-Service | Where-Object {$_.Status -eq "Running"} | Select-Object -First 5
                      }
