FROM mcr.microsoft.com/azure-cli

RUN apt-get update && apt-get install -y git

RUN curl -L -o /usr/local/bin/opa \
https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static && \
chmod +x /usr/local/bin/opa

WORKDIR /app

COPY build.sh .

RUN chmod +x build.sh

CMD ["./build.sh"]
