FROM mcr.microsoft.com/azure-cli

WORKDIR /app

RUN curl -L -o /usr/local/bin/opa \
    https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static && \
    chmod +x /usr/local/bin/opa

COPY policies ./policies
COPY build.sh .

RUN chmod +x build.sh

CMD ["./build.sh"]
